### ISSUE TITLE
Workflow tutorial: cannot create regular file '/mnt/shared-folder/nb.ipynb': No such file or directory

### ISSUE THREAD

**Issue by 94rain** [ploomber/soopervisor#91] opened 2022-06-28 19:30 UTC
I was following this [tutorial](https://soopervisor.readthedocs.io/en/latest/tutorials/workflow.html) to execute a workflow docker container on Ubuntu (logged in as the root user).

After I fixed the issue in #90, it failed while running the following step:
```bash
docker run -i -t \
    --privileged=true -v /var/run/docker.sock:/var/run/docker.sock \
    --volume $SHARED_DIR:/mnt/project \
    --env SHARED_DIR \
    --env PLOOMBER_STATS_ENABLED=false \
    -p 2746:2746 \
    -p 8888:8888 \
    ploomber-workflow
```
It produces the following error:
![image](https://user-images.githubusercontent.com/21193371/176267544-abea7eba-3010-4639-995b-ba8e54b6ca0b.png)

I don't know if there is anything wrong on my side. I don't have any mount folders.

**Comment by edublancas** [comment] 2022-06-28 19:50
Ah, great catch!

The problem is that we recently moved out the example notebook from soorgeon.

Can you edit this file locally: https://github.com/ploomber/soopervisor/blob/566d7773a3af408046d0efbdbd80ad10f77bb620/tutorials/workflow/Dockerfile#L53

and change line 53 for:

https://raw.githubusercontent.com/ploomber/soorgeon/main/examples/machine-learning/nb.py

then try again and see if it works. if it does, please submit a PR with the updated Dockerfile

**Comment by edublancas** [comment] 2022-06-28 20:18
ah no, that's ok. I merged the PR. so what you're saying is that even with the updated URL, you still see the issue, right? the one you reported in the initial comment.

**Comment by edublancas** [comment] 2022-06-29 20:07
ok, I took a look at the Dockerfile and the command but I cannot understand why this is failing. can you help me out?

Maybe try removing the arguments:

```
docker run -i -t ploomber-workflow
```

my guess is that one of them if causing the error

**Comment by 94rain** [comment] 2022-06-29 20:47
> ok, I took a look at the Dockerfile and the command but I cannot understand why this is failing. can you help me out?
> 
> Maybe try removing the arguments:
> 
> ```
> docker run -i -t ploomber-workflow
> ```
> 
> my guess is that one of them if causing the error

I just ran it and the same error still exists

**Comment by 94rain** [comment] 2022-07-05 14:19
I am setting up Github actions to ensure this is not an issue related to my own environment.

**Comment by edublancas** [comment] 2022-07-06 00:47
thanks for working on this. can you open a PR just with the change that fixes the docker command?

let's tackle this first, and then we tackle the docker testing thing. I'll open an issue shortly

**Comment by 94rain** [comment] 2022-07-06 15:29
> thanks for working on this. can you open a PR just with the change that fixes the docker command?
> 
> let's tackle this first, and then we tackle the docker testing thing. I'll open an issue shortly

Sure, I moved a little bit too fast. Just updated #95 with only changes to the tutorial.

**Closed** 2022-07-06 23:00 UTC
